### PR TITLE
feat: add Biome

### PR DESCRIPTION
**Pull request by Kenzo-Wada**
added Biome

related: https://github.com/batijs/bati/discussions/188

### CODE REVIEW

**Comment by Kenzo-Wada** [comment]
Hi, @magne4000 

I hope you will check it out when you have time!

**Comment by magne4000** [comment]
@Kenzo-Wada I'll have a look when tests are passing. Tell me if you need help to fix that.

**Comment by phonzammi** [comment]
Hi @Kenzo-Wada
Are you still working on this PR?

**Comment by magne4000** [comment]
Superseded by #256

**Pull request closed without merging**
