### PR TITLE
qual: adapt boilerplates to latest `vike-{react,vue,solid}`

### PR DESCRIPTION
**Pull request by AurelienLourot**
See https://github.com/vikejs/vike-vue/pull/75

### CODE REVIEW

**Comment by magne4000** [comment]
@AurelienLourot I just merged the `vike-solid` one, released under `vike-solid@0.3.1`

**Comment by AurelienLourot** [comment]
Perfect, I'll update this PR

**Comment by AurelienLourot** [comment]
Done. I have also touched `website/`. I suspect the CI is flaky. What do you think? Can/should we re-run the failed tests? Thanks.

**Comment by magne4000** [comment]
Thanks :clap: (and yeah CI is really flaky... I've re-run failed ones but one still timed out)

**Pull request merged**
