### PR TITLE
qual: adapt react boilerplates to vike-react@0.4.0

### PR DESCRIPTION
**Pull request by AurelienLourot**
`pageContext.pageProps` and `pageContext.title` are deprecated:
https://github.com/vikejs/vike-react/blob/main/packages/vike-react/CHANGELOG.md

See also https://github.com/vikejs/vike-react/pull/50

@magne4000 if that's fine with you, I'll do similar changes to all `{react,vue,solid}*` boilerplates

### CODE REVIEW

**Comment by brillout** [comment]
Actually, I've updated https://vike.dev/head and, as you can see in the updated docs, setting the title over `data.title` isn't documented. I'm about to make a PR updating vike-react explaining why.

**Comment by AurelienLourot** [comment]
Thanks @brillout. Documenting all the vike extensions is also on my radar. But this PR is still correct, right?

**Comment by AurelienLourot** [comment]
I see @brillout, I sense that you'd also like to stop supporting `pageContext.data.title` and instead ask the user to:
1. set `pageContext.data.whateverTitle` in their data hook, and
2. use `pageContext.data.whateverTitle` in their `+title.js`.

Correct? Happy to adapt all the examples and boilerplates everywhere if that's the case.

**Comment by brillout** [comment]
My idea is this: https://vike.dev/head#:~:text=const%20%7B%20rocket%20%7D%20%3D%20useData(). PR is on the way.

**Comment by brillout** [comment]
But it doesn't work: https://github.com/vikejs/vike-react/pull/70/files#diff-a96b0be2b21bc541b4234f17fc1bd2d20bdb901dbe006dd996ed006184699206R27. Let me think and come up with something else (I've a reliable trick in mind but I'm not sure I want to complexify things). I guess I will end up with `pageContext.data` as you suggest. The DX isn't as nice but it's fine.

**Comment by phonzammi** [comment]
> But it doesn't work

I think it's because you haven't remove `description` in another example's config

**Comment by AurelienLourot** [comment]
Converted into a draft for now. I'll rework this once https://github.com/vikejs/vike-react/pull/70 gets released

**Comment by AurelienLourot** [comment]
I'm happy with this now. Let me know what you think

**Comment by magne4000** [comment]
LGTM! If you are still up for it, let's do the same for vue and solid.

**Comment by AurelienLourot** [comment]
Yes, already on it: https://github.com/vikejs/vike-vue/pull/70

**Pull request merged**
