### PR TITLE
add compiled

### PR DESCRIPTION
**Pull request by nitedani**

### CODE REVIEW

**Comment by nitedani** [comment]
Is this missing something?

**Comment by magne4000** [comment]
@nitedani Thanks for the PR!


> Is this missing something?

Yes, as this is a React only lib, we would need warnings in the UI/CLI if React is not selected when choosing Compiled.
For this, you need to define a [rule](https://github.com/batijs/bati/blob/main/packages/features/src/rules/rules.ts).
Each rule must first define a [RuleMessage](https://github.com/batijs/bati/blob/main/packages/features/src/rules/enum.ts), then the [rule](https://github.com/batijs/bati/blob/main/packages/features/src/rules/rules.ts) itself.
After that, each rule must be used in the [website](https://github.com/batijs/bati/blob/main/website/components/RulesMessages.tsx) and the [cli](https://github.com/batijs/bati/blob/main/packages/cli/rules.ts).

You can follow existing rules as examples (try using `--authjs` or selecting `AuthJS` without a server in the UI to see a warning).

**Comment by magne4000** [comment]
🚀

**Comment by nitedani** [comment]
It doesn't work, `pnpm create @batijs/app --react --compiled` doesn't create anything Compiled related.

**Comment by magne4000** [comment]
Fixed in https://github.com/batijs/bati/pull/153 (the flag is now `--compiled-css`).

**Comment by magne4000** [comment]
Also I'm thinking that `react` boilerplate should be updated to take into account this new flag.
You can see in https://github.com/batijs/bati/blob/main/boilerplates/react/files/layouts/LayoutDefault.tsx for instance that we have conditionals based on the presence of `tailwind` or not. We should probably have the same thing for `compiled`.
@nitedani Would that interest you to complete `compiled` integration this way?

There is some [documentation on how to use bati conditional syntax](https://github.com/batijs/bati/blob/main/boilerplates/README.md).

**Comment by nitedani** [comment]
Ok, I'll add it.

**Pull request merged**
