### PR TITLE
Create tooltip for presets

### PR DESCRIPTION
**Pull request by Kenzo-Wada**
Discussion: https://github.com/batijs/bati/pull/127#issuecomment-1838665393

Sorry for being late to create PR...! 

# What I want to be checked
- the sentence of tooltips
- styles of component

# screenshot
Screenshot from 2023-12-09 00-57-48

### CODE REVIEW

**Comment by magne4000** [comment]
Thanks! I'll soon take a look at it. I'm also workinbg on some other tooltips on my side, and I need to fix the issue in the CI.

**Comment by magne4000** [comment]
@Kenzo-Wada please take a look at https://github.com/batijs/bati/pull/140
It defines 2 new components `Tooltip` and `EnrichedTooltip`.
Also CI is fixed on main, you'll need to rebase.

**Comment by Kenzo-Wada** [comment]
@magne4000 

i've updated to use Tooltip in this commit!

**Comment by magne4000** [comment]
@Kenzo-Wada :rocket: Thanks again!

**Pull request merged**
